//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeJS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSDBEntities : DbContext
    {
        public POSDBEntities()
            : base("name=POSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLCATAGORY> TBLCATAGORies { get; set; }
        public virtual DbSet<TBLCUSTOMER> TBLCUSTOMERs { get; set; }
        public virtual DbSet<TBLLOGIN> TBLLOGINs { get; set; }
        public virtual DbSet<TBLPAYMENT> TBLPAYMENTs { get; set; }
        public virtual DbSet<TBLPRODUCT> TBLPRODUCTs { get; set; }
        public virtual DbSet<TBLPURCHASE> TBLPURCHASEs { get; set; }
        public virtual DbSet<TBLSUPPLIER> TBLSUPPLIERs { get; set; }
    }
}
