//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCUSTOMER
    {
        public int CustomerId { get; set; }
        public string MemberCrd { get; set; }
        public string Cname { get; set; }
        public string CAddress { get; set; }
        public string CPhone { get; set; }
        public string CEmail { get; set; }
        public string Point { get; set; }
        public string Remarks { get; set; }
    }
}
