//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPURCHASE
    {
        public int PurchaseId { get; set; }
        public string SupplierId { get; set; }
        public string MemoNo { get; set; }
        public Nullable<System.DateTime> Pdate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Remarks { get; set; }
        public string Productd { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
