//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPRODUCT
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProDesc { get; set; }
        public string ProBarCode { get; set; }
        public byte[] ProImage { get; set; }
        public string SupplierId { get; set; }
        public string CatagoryId { get; set; }
        public Nullable<decimal> UnitInStock { get; set; }
        public Nullable<decimal> ReorderLevel { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string unit { get; set; }
    }
}
