//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeJS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPAYMENT
    {
        public int PaymentId { get; set; }
        public string SupplierId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string MemoNo { get; set; }
        public string PayBy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
    }
}
